In [ ]:
# Notebook 02: Data Preprocessing

## MSc Data Science Dissertation
### University of Hertfordshire

**Project Title**

Explainable Machine Learning versus Deep Learning for Early Disease Prediction: A Multi-Dataset Comparative Study

---

### Objectives

This notebook prepares the Cleveland Heart Disease dataset for machine learning and deep learning experiments by:

- loading the raw data
- assigning meaningful feature names
- converting the target variable into a binary classification problem
- handling missing values
- splitting the dataset
- scaling numerical features
- exporting processed datasets for modelling

In [ ]:
## Purpose of this notebook

This notebook prepares the Cleveland Heart Disease dataset for machine learning and deep learning experiments.

The preprocessing pipeline is designed to ensure that the data are clean, consistent and reproducible before model development.
The same workflow will later be applied to the diabetes and breast cancer datasets to support fair comparison across multiple clinical datasets.

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [17]:
PROJECT_ROOT = Path.cwd().parent

DATA_PATH = PROJECT_ROOT / "data"
RAW_PATH = DATA_PATH / "raw"
PROCESSED_PATH = DATA_PATH / "processed"

PROCESSED_PATH.mkdir(exist_ok=True)
# Dataset configuration
DATASET_NAME = "heart_disease"
DATASET_FILE = "processed.cleveland.data"

In [18]:
columns = [
    "age",
    "sex",
    "cp",
    "trestbps",
    "chol",
    "fbs",
    "restecg",
    "thalach",
    "exang",
    "oldpeak",
    "slope",
    "ca",
    "thal",
    "target"
]

In [29]:
df = pd.read_csv(
    RAW_PATH / DATASET_NAME / DATASET_FILE,
    names=columns,
    na_values="?"
)

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

In [ ]:
## Dataset Overview

Before preprocessing, the dataset is inspected to understand its size, structure, data types and potential quality issues.
This provides an overview of the data and identifies any missing values or incorrect data types that require further processing.

In [30]:
print("Dataset Shape:", df.shape)

df.info()

Dataset Shape: (303, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    float64
 1   sex       303 non-null    float64
 2   cp        303 non-null    float64
 3   trestbps  303 non-null    float64
 4   chol      303 non-null    float64
 5   fbs       303 non-null    float64
 6   restecg   303 non-null    float64
 7   thalach   303 non-null    float64
 8   exang     303 non-null    float64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    float64
 11  ca        299 non-null    float64
 12  thal      301 non-null    float64
 13  target    303 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 33.3 KB

In [ ]:
## Descriptive Statistics

Summary statistics provide an overview of the distribution of each feature, helping identify unusual values and understand
the range of measurements before preprocessing.

In [31]:
missing = df.isnull().sum()

print(missing)

missing[missing > 0]

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          4
thal        2
target      0
dtype: int64

ca      4
thal    2
dtype: int64

In [ ]:
## Target Variable Transformation

The original Cleveland Heart Disease dataset contains five diagnostic categories:

- 0 = No heart disease
- 1–4 = Presence of heart disease

Following common practice in the literature and the approved dissertation proposal, the target variable is converted 
into a binary classification problem.

Binary classification allows consistent comparison between classical machine learning models and deep neural networks 
while reflecting the practical clinical task of identifying whether heart disease is present.

In [22]:
df["target"] = np.where(df["target"] > 0, 1, 0)

df["target"].value_counts()

target
0    164
1    139
Name: count, dtype: int64

In [32]:
class_counts = df["target"].value_counts()

print(class_counts)

print()

print(class_counts / len(df) * 100)

target
0    164
1     55
2     36
3     35
4     13
Name: count, dtype: int64

target
0    54.125413
1    18.151815
2    11.881188
3    11.551155
4     4.290429
Name: count, dtype: float64

In [33]:
class_counts = df["target"].value_counts()

print(class_counts)

print()

print(class_counts / len(df) * 100)

target
0    164
1     55
2     36
3     35
4     13
Name: count, dtype: int64

target
0    54.125413
1    18.151815
2    11.881188
3    11.551155
4     4.290429
Name: count, dtype: float64

In [34]:
import numpy as np

print("===== BEFORE =====")
print(df["target"].value_counts())

df["target"] = np.where(df["target"] > 0, 1, 0)

print("\n===== AFTER =====")
print(df["target"].value_counts())

print("\nUnique values:")
print(df["target"].unique())

print("\nData type:")
print(df["target"].dtype)

===== BEFORE =====
target
0    164
1     55
2     36
3     35
4     13
Name: count, dtype: int64

===== AFTER =====
target
0    164
1    139
Name: count, dtype: int64

Unique values:
[0 1]

Data type:
int64

In [ ]:
## Binary Target Transformation

The original Cleveland dataset contains five diagnostic classes:

0 = No Heart Disease

1–4 = Presence of Heart Disease

Following common practice in the literature, and consistent with the approved dissertation proposal, 
the target variable is converted into a binary classification problem:

- 0 = No Disease
- 1 = Disease

This transformation supports clinically meaningful evaluation using machine learning classifiers.

In [23]:
imputer = SimpleImputer(strategy="most_frequent")

df[["ca", "thal"]] = imputer.fit_transform(df[["ca", "thal"]])

In [24]:
X = df.drop("target", axis=1)

y = df["target"]

In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [26]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [27]:
train_df = pd.DataFrame(X_train_scaled, columns=X.columns)
train_df["target"] = y_train.reset_index(drop=True)

test_df = pd.DataFrame(X_test_scaled, columns=X.columns)
test_df["target"] = y_test.reset_index(drop=True)

train_df.to_csv(
    PROCESSED_PATH / "heart_train_processed.csv",
    index=False
)

test_df.to_csv(
    PROCESSED_PATH / "heart_test_processed.csv",
    index=False
)

print("Processed datasets saved successfully.")

Processed datasets saved successfully.

In [28]:
print("Training set:", train_df.shape)

print("Testing set:", test_df.shape)

train_df.head()

Training set: (242, 14)
Testing set: (61, 14)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,-0.729485,0.68313,0.870169,-0.395692,0.458139,-0.411196,1.022996,0.708371,-0.696177,-0.445445,0.675060,-0.689715,1.179973,1
1,0.050166,0.68313,-1.184278,-0.054513,0.230598,-0.411196,-0.981579,0.222495,-0.696177,-0.891627,-0.958585,-0.689715,-0.878070,0
2,-0.061212,-1.46385,-1.184278,0.059213,0.723605,2.431930,1.022996,0.399178,1.436416,-0.891627,-0.958585,0.445734,-0.878070,0
3,-0.061212,0.68313,-1.184278,-1.305501,1.121803,-0.411196,-0.981579,0.266666,-0.696177,-0.891627,-0.958585,-0.689715,1.179973,0
4,0.272924,-1.46385,0.870169,0.514117,-0.167601,-0.411196,-0.981579,-1.190962,1.436416,-0.713154,0.675060,-0.689715,1.179973,1

In [ ]:
## Missing Value Treatment

The Cleveland Heart Disease dataset contains a small number of missing values in the **ca** and **thal** variables.

Removing these records would unnecessarily reduce the sample size. Therefore, missing values are imputed using
the most frequent category, preserving all observations while maintaining the categorical nature of these variables.

In [35]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy="most_frequent")

df[["ca", "thal"]] = imputer.fit_transform(df[["ca", "thal"]])

In [36]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [37]:
X = df.drop("target", axis=1)
y = df["target"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (303, 13)
Target shape: (303,)

In [38]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training set:", X_train.shape)
print("Testing set:", X_test.shape)

Training set: (242, 13)
Testing set: (61, 13)

In [ ]:
## Train–Test Split

The dataset is divided into training (80%) and testing (20%) subsets.

Stratified sampling is used to preserve the proportion of patients with and without heart disease in both subsets. 
This ensures that model evaluation is representative and reproducible.

A fixed random state of 42 is used to support reproducibility.

In [39]:
print("Training target distribution:")
print(y_train.value_counts())

print("\nTesting target distribution:")
print(y_test.value_counts())

Training target distribution:
target
0    131
1    111
Name: count, dtype: int64

Testing target distribution:
target
0    33
1    28
Name: count, dtype: int64

In [ ]:
## Feature Standardisation

Machine learning algorithms such as Logistic Regression and Deep Neural Networks are sensitive to differences in feature scales.
Therefore, numerical features are standardised using the StandardScaler.

The scaler is fitted only on the training data to prevent information leakage from the test set.
The same fitted scaler is then applied to the testing data.

In [40]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [48]:
import joblib

MODEL_PATH = PROJECT_ROOT / "models"

MODEL_PATH.mkdir(exist_ok=True)

joblib.dump(
    scaler,
    MODEL_PATH / "heart_scaler.pkl"
)

print("Scaler saved successfully.")

Scaler saved successfully.

In [43]:
X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns=X.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns=X.columns,
    index=X_test.index
)

In [44]:
X_train_scaled.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
180,-0.729485,0.68313,0.870169,-0.395692,0.458139,-0.411196,1.022996,0.708371,-0.696177,-0.445445,0.675060,-0.689715,1.179973
208,0.050166,0.68313,-1.184278,-0.054513,0.230598,-0.411196,-0.981579,0.222495,-0.696177,-0.891627,-0.958585,-0.689715,-0.878070
167,-0.061212,-1.46385,-1.184278,0.059213,0.723605,2.431930,1.022996,0.399178,1.436416,-0.891627,-0.958585,0.445734,-0.878070
105,-0.061212,0.68313,-1.184278,-1.305501,1.121803,-0.411196,-0.981579,0.266666,-0.696177,-0.891627,-0.958585,-0.689715,1.179973
297,0.272924,-1.46385,0.870169,0.514117,-0.167601,-0.411196,-0.981579,-1.190962,1.436416,-0.713154,0.675060,-0.689715,1.179973

In [45]:
train_processed = X_train_scaled.copy()
train_processed["target"] = y_train

test_processed = X_test_scaled.copy()
test_processed["target"] = y_test

In [46]:
train_processed.to_csv(
    PROCESSED_PATH / "heart_train_processed.csv",
    index=False
)

test_processed.to_csv(
    PROCESSED_PATH / "heart_test_processed.csv",
    index=False
)

print("Processed datasets saved successfully!")

Processed datasets saved successfully!

In [47]:
print(train_processed.shape)
print(test_processed.shape)

train_processed.head()

(242, 14)
(61, 14)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
180,-0.729485,0.68313,0.870169,-0.395692,0.458139,-0.411196,1.022996,0.708371,-0.696177,-0.445445,0.675060,-0.689715,1.179973,1
208,0.050166,0.68313,-1.184278,-0.054513,0.230598,-0.411196,-0.981579,0.222495,-0.696177,-0.891627,-0.958585,-0.689715,-0.878070,0
167,-0.061212,-1.46385,-1.184278,0.059213,0.723605,2.431930,1.022996,0.399178,1.436416,-0.891627,-0.958585,0.445734,-0.878070,0
105,-0.061212,0.68313,-1.184278,-1.305501,1.121803,-0.411196,-0.981579,0.266666,-0.696177,-0.891627,-0.958585,-0.689715,1.179973,0
297,0.272924,-1.46385,0.870169,0.514117,-0.167601,-0.411196,-0.981579,-1.190962,1.436416,-0.713154,0.675060,-0.689715,1.179973,1